POST http://simon:Wifi9329.@localhost:8000/api/tasks
Content-Type: application/json

{
    "description" : "Lai simon task",
    "due_datetime" : "2024-07-29 20:02:12",
    "is_done" : false,
    "tasklist" : 13
}