# Generated by Django 5.0.7 on 2024-07-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_tasklist_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due_datetime',
        ),
    ]
