# Generated by Django 5.0.7 on 2024-07-26 06:05

import uuid
from django.db import migrations, models
from random import randint

class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_rename_created_date_task_created_datetime_and_more'),
    ]

    def gen_uuid(apps, schema_editor):
        MyModel = apps.get_model("ToDoList", "TaskList")
        for row in MyModel.objects.all():
            row.slug = uuid.uuid4()
            row.save(update_fields=["slug"])
    
    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tasklist',
            name='slug',
            field=models.SlugField(default="Hello" + str(randint(1,3020320302)), max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, verbose_name='due date & time'),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
