# Generated by Django 5.0.7 on 2024-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_author_authorship_book_authorship_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
