# Generated by Django 5.0.7 on 2024-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_author_end_date_author_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
    ]
