# Generated by Django 5.0.7 on 2024-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0007_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
    ]
