DELETE http://localhost:8000/api/tasklists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzcyMDMxLCJpYXQiOjE3MjI3Njg0MzEsImp0aSI6ImVkNjM4M2VjN2M5MjQ3MGFiM2UxYWRkYzVmZjVhMDVjIiwidXNlcl9pZCI6Mn0.hguXNHNAkv1F_XlS71nxfHS_8u7_1Gt3Z4yHVD3OEAM