GET http://localhost:8000/api/tasklists/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzcwNDU2LCJpYXQiOjE3MjI3NjY4NTYsImp0aSI6IjVlMzcwNjQ5MTc5NzQ1YTFhMzZhNmU4Y2JiZTc5ZmZmIiwidXNlcl9pZCI6Mn0.9ZFpNauumuFmJC3zyS4peHXyKYLvW3_cSbH1DGmRm4E